obstacle_range: 5.5
raytrace_range: 4.5

footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
#robot_radius: 0.17

inflation_radius: 1.00
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: sensor_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
