# vox_1:
#   map_merge:
#     init_pose_x: 24.0
#     init_pose_y: -24.0
#     init_pose_z: 0.0
#     init_pose_roll: 0.0
#     init_pose_pitch: 0.0
#     init_pose_yaw: 0.0
# vox_2:
#   map_merge:
#     init_pose_x: -24.0
#     init_pose_y: -24.0
#     init_pose_z: 0.0
#     init_pose_roll: 0.0
#     init_pose_pitch: 0.0
#     init_pose_yaw: 0.0
# vox_3:
#   map_merge:
#     init_pose_x: 24.0
#     init_pose_y: 24.0
#     init_pose_z: 0.0
#     init_pose_roll: 0.0
#     init_pose_pitch: 0.0
#     init_pose_yaw: 0.0
vox_1:
  map_merge:
    init_pose_x: 24.0
    init_pose_y: -24.0
    init_pose_z: 0.0
    init_pose_roll: 0.0
    init_pose_pitch: 0.0
    init_pose_yaw: 0.0
vox_2:
  map_merge:
    init_pose_x: 20.0
    init_pose_y: -24.0
    init_pose_z: 0.0
    init_pose_roll: 0.0
    init_pose_pitch: 0.0
    init_pose_yaw: 0.0
vox_3:
  map_merge:
    init_pose_x: 16.0
    init_pose_y: -24.0
    init_pose_z: 0.0
    init_pose_roll: 0.0
    init_pose_pitch: 0.0
    init_pose_yaw: 0.0